force-app/main/default/objects/Ad__c/Ad__c.object-meta.xml
<CustomObject>
    <label>広告</label>
    <pluralLabel>広告</pluralLabel>
    <nameField>
        <label>広告名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject> 

force-app/main/default/objects/Ad__c/fields/AdCode__c.field-meta.xml
<CustomField>
    <fullName>AdCode__c</fullName>
    <label>広告コード</label>
    <length>50</length>
    <type>Text</type>
</CustomField> 

force-app/main/default/objects/Ad__c/fields/AdGroup__c.field-meta.xml
<CustomField>
    <fullName>AdGroup__c</fullName>
    <label>広告グループ</label>
    <referenceTo>AdGroup__c</referenceTo>
    <relationshipLabel>広告</relationshipLabel>
    <relationshipName>Ads</relationshipName>
    <type>MasterDetail</type>
</CustomField> 

force-app/main/default/objects/Ad__c/fields/Clicks__c.field-meta.xml
<CustomField>
    <fullName>Clicks__c</fullName>
    <label>クリック数</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField> 

force-app/main/default/objects/Ad__c/fields/CTR__c.field-meta.xml
<CustomField>
    <fullName>CTR__c</fullName>
    <label>クリック率</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField> 

force-app/main/default/objects/Ad__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>説明文</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField> 

force-app/main/default/objects/Ad__c/fields/DestinationURL__c.field-meta.xml
<CustomField>
    <fullName>DestinationURL__c</fullName>
    <label>リンク先URL</label>
    <type>Url</type>
</CustomField> 

force-app/main/default/objects/Ad__c/fields/HeadLine__c.field-meta.xml
<CustomField>
    <fullName>HeadLine__c</fullName>
    <label>見出し</label>
    <length>255</length>
    <type>Text</type>
</CustomField> 

force-app/main/default/objects/Ad__c/fields/Impressions__c.field-meta.xml
<CustomField>
    <fullName>Impressions__c</fullName>
    <label>インプレッション数</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField> 

force-app/main/default/objects/Ad__c/fields/MediaType__c.field-meta.xml
<CustomField>
    <fullName>MediaType__c</fullName>
    <label>メディアタイプ</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>画像</fullName>
                <default>true</default>
                <label>画像</label>
            </value>
            <value>
                <fullName>動画</fullName>
            </value>
            <value>
                <fullName>テキスト</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField> 

force-app/main/default/objects/Ad__c/fields/MediaURL__c.field-meta.xml
<CustomField>
    <fullName>MediaURL__c</fullName>
    <label>メディアURL</label>
    <type>Url</type>
</CustomField> 

force-app/main/default/objects/AdGroup__c/AdGroup__c.object-meta.xml
<CustomObject>
    <label>広告グループ</label>
    <pluralLabel>広告グループ</pluralLabel>
    <nameField>
        <label>広告グループ名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject> 

force-app/main/default/classes/AdSetup.cls
public class AdSetup {
    public static void createAdObject() {
        MetadataService.CustomObject adObj = new MetadataService.CustomObject();
        adObj.fullName = 'Ad__c';
        adObj.label = '広告';
        adObj.pluralLabel = '広告';
        adObj.nameField = new MetadataService.CustomField();
        adObj.nameField.type_x = 'Text';
        adObj.nameField.label = '広告名';
        adObj.deploymentStatus = 'Deployed';
        adObj.sharingModel = 'ReadWrite';

        MetadataService.CustomField[] fields = new List<MetadataService.CustomField>();
        
        fields.add(MetadataServiceHelper.createMasterDetailField('AdGroup__c', '広告グループ', 'AdGroup__c'));
        fields.add(MetadataServiceHelper.createTextField('AdCode__c', '広告コード', 50));
        fields.add(MetadataServiceHelper.createURLField('DestinationURL__c', 'リンク先URL'));
        fields.add(MetadataServiceHelper.createTextField('HeadLine__c', '見出し', 255));
        fields.add(MetadataServiceHelper.createLongTextAreaField('Description__c', '説明文', 32768));
        fields.add(MetadataServiceHelper.createTextField('MediaURL__c', 'メディアURL', 255));
        fields.add(MetadataServiceHelper.createPicklistField('MediaType__c', 'メディアタイプ', 
            new List<String>{'画像', '動画', 'テキスト'}));
        fields.add(MetadataServiceHelper.createNumberField('Impressions__c', 'インプレッション数', 18, 0));
        fields.add(MetadataServiceHelper.createNumberField('Clicks__c', 'クリック数', 18, 0));
        fields.add(MetadataServiceHelper.createNumberField('CTR__c', 'クリック率', 18, 2));

        adObj.fields = fields;
    }
} 